# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DBIx-DataStore
version:      0.95
version_from: lib/DBIx/DataStore.pm
installdirs:  site
requires:
    Data::Page:                    0
    DBI:                           0
    Test::More:                    0
    YAML::Syck:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
